NAME = Bureaucrat

DIR_OBJS = .obj

INCLUDE_DIR = includes

FLAGS = -Wall -Werror -Wextra -std=c++98

DFLAGS = -MD -MP

SRC = Bureaucrat.cpp \
		main.cpp

SRC_PATH = src/

CC = c++

CHECK = ✅
RED = $(shell tput setaf 1)
CROSS = ❌
GREEN = $(shell tput setaf 2)
RESET_COLOR = $(shell tput sgr0)
CYAN = $(shell tput setaf 6)

OBJ = $(addprefix $(DIR_OBJS)/, $(SRC:.cpp=.o))
DEP = $(OBJ:.o=.d)

all:$(NAME)

IFLAGS = -I$(INCLUDE_DIR)

-include $(DEP)

$(DIR_OBJS)/%.o: $(SRC_PATH)%.cpp Makefile
	@mkdir -p  $(dir $@)
	@$(CC)  $(IFLAGS) $(FLAGS) $(DFLAGS) -c $< -o $@
	@echo "$(CYAN) $< created $(CHECK)$(RESET_COLOR)"

$(NAME): $(OBJ)
	@$(CC) $(OBJ) -o $(NAME)
	@echo "$(GREEN)$(NAME) created $(CHECK)$(RESET_COLOR) "

clean:
	@rm -rf $(DIR_OBJS)
	@echo "$(RED)$(DIR_OBJS) removed $(CROSS)$(RESET_COLOR) "

fclean: clean
	@rm -f $(NAME)

FORCE:

re: fclean all

.PHONY: all re clean fclean re FORCE